### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by elenimijalis** [TAMU-CPT/lims-frontend#15]
- [ ] add fail state to not submit env sample OR lysate if storage location is duplicated (somehow prompt the user to fix the storage error.. but then what the storage is ok but the envsample/lysate post is bad? need to discuss this)
- [ ] add storage rows to detail views of envsamples
- [ ] it's not intuitive how to get from lysate to dnaprep. right now you have to click on phage in the lysate detail form

**Comment by hexylena** [comment]
As for "lysate -> dna prep", I'm assuming that once a phage object is created, people will visit that as the central hub, rather than visiting lysate.

**Comment by elenimijalis** [comment]
explain central hub?

**Comment by hexylena** [comment]
I feel like people will go to the phage page, rather than looking to create a lysate from the DNA prep. I can see what you're thinking though, since the phage will still be "Unnamed Phage". Perhaps we should support this workflow as well.
